# Generated by Django 3.0.6 on 2020-05-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200513_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubtypes',
            name='product_type',
        ),
    ]
