# Generated by Django 3.0.6 on 2020-05-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='quantity',
            field=models.IntegerField(max_length=255),
        ),
    ]
