# Generated by Django 3.0.6 on 2020-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200514_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
